spring:
  application:
    name: razorpay

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay}
    baseline-on-migrate: true
    locations: classpath:db/migration/

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

#server:
#  servlet:
#    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: TRACE
    com.ermapsh: DEBUG    # Replace with your base package

payment:
  order:
    default_order_expiry_minutes: 30
  simulator:
    poll-interval-ms: 5000
    chaos-mod: NORMAL #FAILURE/SUCCESS/TIMEOUT
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 2
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

vault:
  master-key: awn7B/A/8FfxDCgliiWlYWKqBIU7BTeXA9/c5eWKXpM=
jwt:
  secret-key: Vj1yrAp3xRycy0HOIbCCBtpx/EAotKV7cbqyrHzu3GMnvlE8BqdCyOwUJgjXE1rWUSx9f0hZ+b1YVTI5RSQcEg==
app:
  rate-limit:
      method: fixed
    use-case:
      api-key:
        requests-per-minute: 60