spring:
  application:
    name: razorpay

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.ermapsh: DEBUG    # Replace with your base package

merchant:
  id: 9472c030-caf9-46e5-b5f4-79a8482a937a

payment:
  order:
    default_order_expiry_minutes: 30