spring:
  application:
    name: razorpay

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG

merchant:
  id: 2d749734-bfd8-4720-94b6-2ea2bbc30512