spring:
  application:
    name: razorpay

  datasource:
    url: jdbc:postgresql://razorpay-sp.cdmmyguky359.ap-south-1.rds.amazonaws.com:5432/postgres
    username: root
    password: Mapsh8055

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.ermapsh: DEBUG    # Replace with your base package

merchant:
  id: 9472c030-caf9-46e5-b5f4-79a8482a937a

payment:
  order:
    default_order_expiry_minutes: 30
  simulator:
    poll-interval-ms: 5000
    chaos-mod: NORMAL #FAILURE/SUCCESS/TIMEOUT
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 2
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80
